<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Icons\scribble3.ico</ApplicationIcon>
    <Version>1.3.1</Version>
    <Company>Radish</Company>
    <Product>Scribble</Product>
    <Copyright>© 2026 Radish</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icons\color3.png" />
    <None Remove="Icons\copy3.png" />
    <None Remove="Icons\new3.png" />
    <None Remove="Icons\open3.png" />
    <None Remove="Icons\print3.png" />
    <None Remove="Icons\redo3.png" />
    <None Remove="Icons\save3.png" />
    <None Remove="Icons\scribble2.ico" />
    <None Remove="Icons\undo3.png" />
    <None Remove="Icons\width3.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icons\scribble3.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\color3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\copy3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\new3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\open3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\print3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\redo3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\save3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\scribble2.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\undo3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\width3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
